pygments: true
auto: true
permalink: none
hashtag: '#MiddWAG'
twitter_search: 'MiddWAG'
github_login: 'MiddWAG'
github_repo: 'middwag.github.com'
github_language: ['Javascript', 'Ruby', 'PHP', 'Python']
email: nate.beatty@gmail.com
